name: gis_osm
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^4.0.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
