name: gis_osm
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  intl:
  flutter_map:
  geolocator:
  latlong2:
  flutter_bloc:
  cupertino_icons:
  equatable:
  shared_preferences:
  image_picker:
  image_cropper:
  flutter_colorpicker:
  http:
  provider:
  font_awesome_flutter:
  cloud_firestore:
  firebase_core:
  web_socket_channel:
  firebase_auth:
  shared_preferences_android:
  firebase_storage:
  firebase_messaging:
  flutter_notification_channel:
  flutter_map_marker_cluster:
  flutter_map_tile_caching:
  cached_network_image:
  permission_handler:
  flutter_localization:
  firebase_database:
  flutter_local_notifications:
  vibration:
  audioplayers:
  google_api_availability:
  connectivity_plus:
  googleapis:
  googleapis_auth:
  flutter_background_service:
  flutter_background_service_ios:
  fluttertoast:
  android_alarm_manager_plus:
  flutter_native_splash:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android:
  image_path: assets/images.jpeg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images.jpeg

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
    - assets/default_avater.png
    - assets/person_marker.png
    - assets/notification.wav