// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Hn5EVcbbEPDumVOz7knEXgldbC3kBUc',
    appId: '1:82838015404:web:a02a7ed52ab5ccf8713e09',
    messagingSenderId: '82838015404',
    projectId: 'gis-osm',
    authDomain: 'gis-osm.firebaseapp.com',
    storageBucket: 'gis-osm.firebasestorage.app',
    measurementId: 'G-6BV19CGFEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-n0rC3-TIFwKf66T7mFCThKYgnJvl1ok',
    appId: '1:82838015404:android:a58dc3976832690c713e09',
    messagingSenderId: '82838015404',
    projectId: 'gis-osm',
    storageBucket: 'gis-osm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZwco58bRsZjGI2CuwYjeHma_ynKBpPaI',
    appId: '1:82838015404:ios:3cfd68c8ec3dc4d0713e09',
    messagingSenderId: '82838015404',
    projectId: 'gis-osm',
    storageBucket: 'gis-osm.firebasestorage.app',
    iosBundleId: 'com.gisosm.gisOsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZwco58bRsZjGI2CuwYjeHma_ynKBpPaI',
    appId: '1:82838015404:ios:3cfd68c8ec3dc4d0713e09',
    messagingSenderId: '82838015404',
    projectId: 'gis-osm',
    storageBucket: 'gis-osm.firebasestorage.app',
    iosBundleId: 'com.gisosm.gisOsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Hn5EVcbbEPDumVOz7knEXgldbC3kBUc',
    appId: '1:82838015404:web:2936dc38f1d8104a713e09',
    messagingSenderId: '82838015404',
    projectId: 'gis-osm',
    authDomain: 'gis-osm.firebaseapp.com',
    storageBucket: 'gis-osm.firebasestorage.app',
    measurementId: 'G-B0SCD2CTK3',
  );
}
